name: Dispatch Workflow Job

on:
  repository_dispatch:
    types: dispatch-workflow-job

jobs:
  build:
    name: Run Job
    runs-on: ubuntu-latest
        
    steps:
    - name: Echo Handler Name
      run: 'echo "Dispatch Handler: ${{ github.event.client_payload.handlerName }}"'
        
    - name: Echo Dispatch Object Scheduled Id
      run: 'echo "Dispatch Object Scheduled: ${{ github.event.client_payload.objectScheduledId }}"'

    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'

    - uses: ./
      with:
        handler-name: ${{ github.event.client_payload.handlerName }}
        object-scheduled-id: ${{ github.event.client_payload.objectScheduledId }}
        twitter-consumer-id: ${{ secrets.TWITTER_CONSUMER_ID }}
        twitter-consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        identity-client-secret: ${{ secrets.IDENTITY_CLIENT_SECRET }}
        github-access-token: ${{ secrets.GH_TOKEN }}
