name: Dispatch Workflow Job

on:
  repository_dispatch:
    types: dispatch-workflow-job

jobs:
  build:
    name: Run Job
    runs-on: ubuntu-latest
        
    steps:
    - name: Echo Workflow Name
      run: 'echo "Dispatch Workflow: ${{ github.event.client_payload.workflowName }}"'
        
    - name: Echo Job Id
      run: 'echo "Dispatch Job: ${{ github.event.client_payload.idJob }}"'

    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'

    - uses: ./
      with:
        workflow: ${{ github.event.client_payload.workflowName }}
        job: ${{ github.event.client_payload.idJob }}
        twitter-consumer-id: ${{ secrets.TWITTER_CONSUMER_ID }}
        twitter-consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        identity-client-secret: ${{ secrets.IDENTITY_CLIENT_SECRET }}
        github-access-token: ${{ secrets.GITHUB_TOKEN }}
