name: .NET Core Action Template

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      working-directory: 'src'
      run: dotnet build --configuration Release
      
      
  test:
    name: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
        
    - uses: ./
      with:
        workflow: 'Thursday'
        twitter-consumer-id: ${{ secrets.TWITTER_CONSUMER_ID }}
        twitter-consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        github-access-token: ${{ secrets.GITHUB_TOKEN }}
